version: '3.8'

services:
  # ------------------------------------
  # 1. MICROSERVICIOS Y GATEWAY
  # ------------------------------------
  ms-catalogo-py:
    build: 
      context: ./ms-catalogo-py
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - ./ms-catalogo-py:/app
      - ./data-externa:/app/data-externa
    env_file:
      - ./ms-catalogo-py/.env
    depends_on:
      ms-recetas-db:
        condition: service_healthy 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/recetas"] 
      interval: 15s 
      timeout: 10s 
      retries: 8 

  ms-valoraciones-nodejs:
    build:
      context: ./ms-valoraciones-nodejs 
      dockerfile: Dockerfile
    restart: always 
    environment:
      # Usamos 'db-valoraciones' (el nombre del servicio que vamos a definir)
      DATABASE_URL: mongodb://user_valoraciones:password_valoraciones@db-valoraciones:27017/valoraciones_db?authSource=admin
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db-valoraciones # <--- La dependencia ahora apunta al servicio correcto

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./api-gateway:/app
      - ./frontend:/app/frontend 
    env_file:
      - ./api-gateway/.env
    command: sh -c "sleep 10 && node server.js"
    depends_on:
      ms-catalogo-py:
        condition: service_healthy 
      ms-valoraciones-nodejs:
        condition: service_started

  # ------------------------------------
  # 2. BASES DE DATOS
  # ------------------------------------
  ms-recetas-db: # Base de datos de Catálogo (PostgreSQL)
    image: postgres:14-alpine
    container_name: ms_recetas_db
    restart: always
    environment:
      POSTGRES_USER: user_recetas
      POSTGRES_PASSWORD: password_recetas
      POSTGRES_DB: recetas_db
    ports:
      - "5432:5432" 
    volumes:
      - recetas_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-valoraciones: # Base de datos de Valoraciones (MongoDB)
    image: mongo:6.0 # Usamos la versión 6.0 que tenías en el bloque anterior
    container_name: db_valoraciones
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_valoraciones
      MONGO_INITDB_ROOT_PASSWORD: password_valoraciones
      MONGO_INITDB_DATABASE: valoraciones_db
    ports:
      - "27018:27017"
    volumes:
      - valoraciones_data:/data/db

# ------------------------------------
# 3. VOLUMENES
# ------------------------------------
volumes:
  recetas_data:
  valoraciones_data: