version: '3.8'

services:
  # ------------------------------------
  # 1. MICROSERVICIOS Y GATEWAY
  # ------------------------------------
  ms-catalogo-py:
    build: 
      context: ./ms-catalogo-py
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - ./ms-catalogo-py:/app
      - ./data-externa:/app/data-externa
    env_file:
      - ./ms-catalogo-py/.env
    depends_on:
      - ms-recetas-db 
    
    # === AJUSTE DE LA TOLERANCIA DEL HEALTHCHECK PARA CI ===
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/recetas"] 
      interval: 15s # Aumentar el intervalo
      timeout: 10s # Dar más tiempo para una respuesta lenta
      retries: 8 # Permitir más reintentos
    # ======================================================

  ms-valoraciones-nodejs:
    build: 
      context: ./ms-valoraciones-nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ms-valoraciones-nodejs:/app
    env_file:
      - ./ms-valoraciones-nodejs/.env
    depends_on:
      - ms-valoraciones-db

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./api-gateway:/app
      - ./frontend:/app/frontend 
    env_file:
      - ./api-gateway/.env
    
    # Espera a que el Catálogo esté COMPLETO y SANO
    depends_on:
      ms-catalogo-py:
        condition: service_healthy 
      ms-valoraciones-nodejs:
        condition: service_started

  # ------------------------------------
  # 2. BASES DE DATOS
  # ------------------------------------
  ms-recetas-db:
    image: postgres:14-alpine
    container_name: ms_recetas_db
    restart: always
    environment:
      POSTGRES_USER: user_recetas
      POSTGRES_PASSWORD: password_recetas
      POSTGRES_DB: recetas_db
    ports:
      - "5432:5432" 
    volumes:
      - recetas_data:/var/lib/postgresql/data

  ms-valoraciones-db:
    image: mongo:6.0
    container_name: ms_valoraciones_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_valoraciones
      MONGO_INITDB_ROOT_PASSWORD: password_valoraciones
    ports:
      - "27017:27017"
    volumes:
      - valoraciones_data:/data/db

# ------------------------------------
# 3. VOLUMENES
# ------------------------------------
volumes:
  recetas_data:
  valoraciones_data: