openapi: 3.0.0
info:
  title: Catálogo de Recetas y Valoraciones API
  version: 1.0.0
  description: API Gateway para la agregación de datos de los Microservicios de Catálogo (Python) y Valoraciones (Node.js).

servers:
  - url: http://localhost:8080/api/v1
    description: Entorno de Desarrollo Local

paths:
  /recetas:
    get:
      tags:
        - Catálogo y Agregación
      summary: Obtiene la lista de recetas con su puntuación media agregada.
      description: Llama a MS-Catálogo (Python) y a MS-Valoraciones (Node.js) para combinar datos.
      responses:
        '200':
          description: Listado exitoso de recetas con sus medias de valoración.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    receta_id:
                      type: string
                      example: REC001
                    titulo:
                      type: string
                      example: Paella de Marisco
                    average_rating:
                      type: number
                      format: float
                      description: Puntuación media obtenida del MS Node.js.
                      example: 4.5
        '500':
          description: Error de orquestación en el Gateway.

  /valoraciones/{recetaId}:
    post:
      tags:
        - Interacción y Valoración
      summary: Envía una nueva valoración para una receta específica.
      description: Redirecciona la petición directamente al MS-Valoraciones (Node.js).
      parameters:
        - name: recetaId
          in: path
          required: true
          schema:
            type: string
          description: ID de la receta a valorar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                puntuacion:
                  type: integer
                  example: 5
                comentario:
                  type: string
                  example: ¡Excelente receta!
      responses:
        '201':
          description: Valoración creada con éxito.
        '400':
          description: Petición inválida.

  /admin/cargar_datos:
    post:
      tags:
        - Administración
      summary: Dispara la ingesta de datos externos (ETL).
      description: Redirecciona la petición al MS-Catálogo (Python) para cargar recetas en la BBDD.
      responses:
        '200':
          description: Proceso de ingesta iniciado.